language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install xlrd
  - pip install pandas
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install flake8

script:
  - py.test

after_success:
  - coveralls
