name: CI

on:
  push:


jobs:
  ci:
    uses: RWTH-EBC/ci_templates/.github/workflows/ci_pipeline.yml@main
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    with:
      PYTHON_VERSION: '3.10'
      PYPI_RELEASE: true
      BUILD_PACKAGE: true
